version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: gambaru
      MYSQL_USER: gambaru
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
#    volumes:
#      - dbdata:/var/lib/mysql
    volumes:
      - ./data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    restart: always
    ports:
      - 8081:80
volumes:
  dbdata: